#include "FireJet.h"
#include "../../Core/Maths/Vector2.h"
#include "../../Core/Renderer/ConsoleColours.h"
#include <Windows.h>

const int MOVEMENT_SPEED = 2; // movement speed for the character 

CHAR_INFO MainCharacter[] = // character sprite 
{ 
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_GREEN },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_GREEN },{ 0 ,BACKGROUND_GREEN },{ 0 ,BACKGROUND_GREEN },{ 0 ,BACKGROUND_SKYBLUE },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_DARK_GREY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_GREEN },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_INTENSITY },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_PINK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BRIGHT_BLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_SKYBLUE },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
	{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },{ 0 ,BACKGROUND_BLACK },
};


//playership class
FireJet::FireJet() 
:m_UpKey(0)
,m_DownKey(0)



, m_bInitialised(true)
{
}

FireJet::~FireJet()
{
}

void FireJet::Initialise(Vector2& position, int UpKey, int DownKey) // setting the position for the sprite in the game
{
	m_UpKey = UpKey;
	m_DownKey = DownKey;
	

	Sprite::Initialise(MainCharacter, Vector2(16, 20)); // for example vector (12,10) is to set the character pixels in the game 12 at x axis and 10 at y axis

	Vector2 startPosition(position.y - (Sprite::GetSize().y *4 ), position.y / 2 - (Sprite::GetSize().x / 12 ));

	SetPosition(startPosition);

	m_bInitialised = true;
}

void FireJet::Update() // updating, so if the key is pressed, it should function.
{
	if (!m_bInitialised)
		return;
	if (UpKeyPressed())
	{
		MoveUp();
	}
	if (DownKeyPressed())
	{
		MoveDown();
	}

}

void FireJet::Render(ASCIIRenderer* pRenderer) //this rendereding function will help show the playership on to the screen
{
	if (!m_bInitialised)
		return;

	Sprite::Render(pRenderer);
	
}

void FireJet::MoveUp() // this function used for moving the sprite UpWords
{
	SetPosition(Vector2(GetPosition().x ,  GetPosition().y - MOVEMENT_SPEED));

	if (GetPosition().y < 0)
	{
		MoveDown();
	}
}

void FireJet::MoveDown() // this function used for moving the sprite DownWords
{
	SetPosition(Vector2(GetPosition().x, GetPosition().y  + MOVEMENT_SPEED ));

	if (GetPosition().y  + GetSize().x > SCREEN_HEIGHT )
	{
		MoveUp();
	}
}

bool FireJet::UpKeyPressed() // when you press the up key so the enemy moves up
{
	return (GetKeyState(m_UpKey) < 0);
}

bool FireJet::DownKeyPressed() // when you press the down key so the enemy moves down	
{
	return (GetKeyState(m_DownKey) < 0);
}
