include "Game/GameObjects/PlayerLives.h"
#include "Core/Renderer/ConsoleColours.h"

CHAR_INFO HealthSprite[Health][Health_WIDTH * Health_HEIGHT] =
{
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
	},
};

PlayerLives::PlayerLives()
	:m_bInitialised(false)
{
}

PlayerLives::~PlayerLives()
{
}

void PlayerLives::Initialise(Vector2& position)
{
	AnimatedSprite::Initialise(&HealthSprite[0][0], Vector3(Health_WIDTH, Health_HEIGHT, Health));

	Vector2 startPosition(position.x + (-30), position.y - (AnimatedSprite::GetSize().y / 2));
	SetPosition(startPosition);

	SetAnimationFrame(0);

	m_bInitialised = true;
}

void PlayerLives::Update(float deltaTime)
{
	if (!m_bInitialised)
		return;
}

void PlayerLives::SetHealthValue(int value)
{
	if (value >= 0 && value < Health)
	{
		SetAnimationFrame(value);
	}
	else
	{
		SetAnimationFrame(0);
	}
}


void PlayerLives::Render(ASCIIRenderer* pRenderer)
{
	if (!m_bInitialised)
		return;

	AnimatedSprite::Render(pRenderer);
}
