#include "ScoreDisplay.h"
#include "../../Core/Renderer/ConsoleColours.h"

CHAR_INFO ScoreDigitSprite[NUM_DIGITS][DIGIT_WIDTH * DIGIT_HEIGHT] = //sprite for the score display which will display "0000" and "123456789" all of them are created
{
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
	{
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK } ,{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BLACK },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },
		{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  } ,{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BRIGHT_RED  },{ ' ' ,BACKGROUND_BLACK },
	},
};

ScoreDisplay::ScoreDisplay()
	:m_bInitialised(false)
{
}

ScoreDisplay::~ScoreDisplay()
{
}

void ScoreDisplay::Initialise(Vector2& position) //This is used for setting up the position for the scoreDisplay on the screen
{
	AnimatedSprite::Initialise(&ScoreDigitSprite[0][0], Vector3(DIGIT_WIDTH, DIGIT_HEIGHT, NUM_DIGITS));

	Vector2 startPosition((AnimatedSprite::GetSize().x * 31) + position.x , position.y - (AnimatedSprite::GetSize().y / 2));
	SetPosition(startPosition);

	SetAnimationFrame(0);

	m_bInitialised = true;
}

void ScoreDisplay::Update(float deltaTime) // this function will help updting the score with in the game when you destroy and enemy ship.
{
	if (!m_bInitialised)
		return;	
}

void ScoreDisplay::SetDigitValue(int value) // this is for setting the number values in the score display and display according to the time .
{
	if (value >= 0 && value < NUM_DIGITS)
	{
		SetAnimationFrame(value);
	}
	else
	{
		SetAnimationFrame(0);
	}
}

void ScoreDisplay::Render(ASCIIRenderer* pRenderer) // this will allow the display to be shown on the screen
{
	if (!m_bInitialised)
		return;

	AnimatedSprite::Render(pRenderer);
}

